name: Deploy to Cloud Run

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: basecamp-dashboard
  REGION: us-central1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for required secrets
        run: |
          if [ -z "${{ secrets.GCP_PROJECT_ID }}" ] || [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "❌ Missing required secrets: GCP_PROJECT_ID and/or GCP_SA_KEY"
            echo "ℹ️  Please set up Google Cloud authentication secrets in repository settings"
            exit 1
          fi
          echo "✅ Required secrets are configured"

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --source . \
            --region $REGION \
            --allow-unauthenticated \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 10

      - name: Show URL
        run: gcloud run services describe $SERVICE --platform managed --region $REGION --format 'value(status.url)'
